/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author Ran
 */
public class Fammy extends javax.swing.JFrame {
        int xMouse;
        int yMouse ;
       int i =0;
    /**
     * Creates new form 
     */
    public Fammy() {
        initComponents();
      
       
        
        
        
        setSize(new java.awt.Dimension(454,340));
        jComboBox1.setVisible(false);
        jComboBox2.setVisible(false);
        jComboBox3.setVisible(false);
        jComboBox4.setVisible(false);
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
        jComboBox3.setEnabled(false);
        jComboBox4.setEnabled(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        view = new javax.swing.JTextField();
        Site = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        famous = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jmoviningbar = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton2.setToolTipText("Close");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 10, 20, 20);

        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view);
        view.setBounds(180, 110, 90, 23);
        getContentPane().add(Site);
        Site.setBounds(180, 170, 250, 30);

        jRadioButton1.setText("Advance Setting");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(340, 220, 140, 23);

        jButton4.setToolTipText("About SF");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(360, 10, 20, 20);

        jButton3.setToolTipText("Minimize");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 10, 20, 20);

        famous.setBorderPainted(false);
        famous.setContentAreaFilled(false);
        famous.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                famousMouseMoved(evt);
            }
        });
        famous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                famousMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                famousMouseReleased(evt);
            }
        });
        famous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                famousActionPerformed(evt);
            }
        });
        getContentPane().add(famous);
        famous.setBounds(140, 270, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/but.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 270, 150, 30);

        jmoviningbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jmoviningbarMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jmoviningbarMouseMoved(evt);
            }
        });
        jmoviningbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmoviningbarMousePressed(evt);
            }
        });
        getContentPane().add(jmoviningbar);
        jmoviningbar.setBounds(0, 0, 450, 30);

        jComboBox1.setBackground(new java.awt.Color(51, 204, 056));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Time For Loading Per Tab", "3 sec", "5 sec", "10 sec", "15 sec", "20 sec", "30 sec", "40 sec" }));
        jComboBox1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboBox1MouseMoved(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(170, 220, 186, 29);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Number Of Tabs", "6", "7", "8", "9", "10" }));
        jComboBox2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboBox2MouseMoved(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(170, 220, 186, 29);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "After Completing Task", "Do Nothing", "Shutdown", "Restart", "Log Off" }));
        jComboBox3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboBox3MouseMoved(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(170, 220, 186, 29);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Default Browser", "Google Chrome", "Opera", "Mozilla Firefox", "Internet Explorer" }));
        jComboBox4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboBox4MouseMoved(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(170, 220, 186, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/siteFammer.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 454, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmoviningbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmoviningbarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y -yMouse);
    }//GEN-LAST:event_jmoviningbarMouseDragged

    private void jmoviningbarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmoviningbarMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jmoviningbarMouseMoved

    private void jmoviningbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmoviningbarMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jmoviningbarMousePressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected())
        {    
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fammy.png")));
            jLabel1.setBounds(0, 0, 454, 500);
            setSize(new java.awt.Dimension(454,500));
            Site.setBounds(170, 130, 250, 30);
            view.setBounds(170, 70, 90, 23);
            jRadioButton1.setBounds(50, 180, 140, 15);
            jRadioButton1.setText("Hide Advance Setting");
            jComboBox1.setBounds(168, 215, 186, 29);
            jComboBox2.setBounds(168, 279, 186, 29);
            jComboBox3.setBounds(168, 348, 186, 29);
            jComboBox4.setBounds(168, 408, 186, 29);
            famous.setBounds(143, 460, 150, 30);
            jComboBox1.setVisible(true);
            jComboBox2.setVisible(true);
            jComboBox3.setVisible(true);
            jComboBox4.setVisible(true);
            jComboBox1.setEnabled(true);
            jComboBox2.setEnabled(true);
            jComboBox3.setEnabled(true);
            jComboBox4.setEnabled(true);
            jLabel2.setBounds(143, 460, 150, 30);
        }
        
        else
        {
           jLabel1.setBounds(0, 0, 454, 340);
           famous.setBounds(140, 250, 150, 30); 
           jLabel2.setBounds(140, 250, 150, 30);
           jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/siteFammer.png")));
          jRadioButton1.setBounds(340, 220, 140, 23);
           setSize(new java.awt.Dimension(454,340));
           jRadioButton1.setText("Advance Setting");
           view.setBounds(180, 110, 90, 23);
           Site.setBounds(180, 170, 250, 30);
           jComboBox1.setVisible(false);
           jComboBox2.setVisible(false);
           jComboBox3.setVisible(false);
           jComboBox4.setVisible(false);
           jComboBox1.setEnabled(false);
           jComboBox2.setEnabled(false);
           jComboBox3.setEnabled(false);
           jComboBox4.setEnabled(false);


        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1FocusGained

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseMoved
        // TODO add your handling code here:
    
     
    }//GEN-LAST:event_jComboBox1MouseMoved

    private void jComboBox2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox2MouseMoved

    private void jComboBox3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox3MouseMoved

    private void jComboBox4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox4MouseMoved

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
             
    }//GEN-LAST:event_viewActionPerformed

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
       jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/but.png")));      
    }//GEN-LAST:event_jLabel1MouseMoved

    private void famousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_famousActionPerformed
        // TODO add your handling code here:
         String site = Site.getText();
         String commandExec = "";
         int time =0;
         int tabs =0;
         String task;  
         String browser = null;
         Runtime rt = Runtime.getRuntime();
         Runtime rr = Runtime.getRuntime();
         int views;
         views = Integer.parseInt(view.getText());
       
   if(jRadioButton1.isSelected())
       
   {  
       if(site.isEmpty()||jComboBox1.getSelectedIndex()==0||jComboBox2.getSelectedIndex()==0||jComboBox3.getSelectedIndex()==0||jComboBox4.getSelectedIndex()==0)
       {
        JOptionPane.showMessageDialog(this, "Please Fille the Detail");
       }
       
       else
       {
       switch (jComboBox1.getSelectedIndex())
  
        {
                      
            case 1 : time = 3000;         
                     break;
                     
            case 2 : time = 5000;
                      break;
                      
            case 3 : time = 10000;
                     break;
                     
            case 4 : time = 15000;
                     break;
                     
                     
           case 5 : time = 20000;
                     break;         
                     
           case 6 : time = 30000;
                     break;
                     
           case 7 : time = 40000;
                     break; 
   

        }
  
   
            switch(jComboBox2.getSelectedIndex())
   {
            
            case 1 : tabs = 6;         
                     break;
                     
            case 2 : tabs = 7;
                      break;
                      
            case 3 : tabs = 8;
                     break;
                     
            case 4 : tabs = 9;
                     break;
                     
                     
            case 5 : tabs = 10;
                     break;         
                     
  
   }

  
   
    switch(jComboBox4.getSelectedIndex())
   {  
           case 1 : browser = "chrome.exe";         
                     break;
                     
            case 2 : browser = "Opera.exe";
                      break;
                      
            case 3 : browser = "Firefox.exe";
                     break;
                     
            case 4 : browser = "iexplore.exe";
                     break;
  
   }
       
      
       
      
       
       
   for (i = 0;i<=views;i++)
         {
        
             try{
              Desktop desktop = java.awt.Desktop.getDesktop();
              URI oURL = new URI(site);
              desktop.browse(oURL);
              Thread.sleep(time);
            
              if(i==tabs)
            { 
                 
                rt.exec("taskkill /F /IM " + browser);
                tabs = tabs + tabs;
                 
            }
            
           
            
            }
            
            
         
         catch(Exception e)
         {
         JOptionPane.showMessageDialog(this, "Please Enter the correct url");
         
         
         }
         
         }
        
        try {
         rt.exec("taskkill /F /IM  "  + browser);
        
        
        if(jComboBox3.getSelectedIndex()==2)
        {   rr.exec("shutdown -s -t 5 ");
        
        }
        else if(jComboBox3.getSelectedIndex()==3)
         {   rr.exec("shutdown -r -t 5 ");
        
        }
        else if(jComboBox3.getSelectedIndex()==4)
         {   rr.exec("shutdown -l -t 5 ");
        
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
   
   
   
   
       }
 
   }
else



         for (;i<=views;i++)
         {
            
             try{
            
              int tab = 5;
              Desktop desktop = java.awt.Desktop.getDesktop();
              URI oURL = new URI(site);
              desktop.browse(oURL);
              Thread.sleep(3000);
            
              if(i==tab)
            { 
                 
                rt.exec("taskkill /F /IM  chrome.exe ");
                tab = tab + 7;
                 
            }
            
           
            
            }
            
            
         
         catch(Exception e)
         {
         JOptionPane.showMessageDialog(this, e.getMessage());
         
         
         }
         
         }
        
        try {
         rt.exec("taskkill /F /IM  chrome.exe ");
         
        } catch (Exception e) {
            
        }
        
    }//GEN-LAST:event_famousActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void famousMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_famousMouseMoved
        // TODO add your handling code here:
       jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/butmove.png")));
    }//GEN-LAST:event_famousMouseMoved

    private void famousMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_famousMousePressed
        // TODO add your handling code here:
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/butpre.png")));
    }//GEN-LAST:event_famousMousePressed

    private void famousMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_famousMouseReleased
        // TODO add your handling code here:
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/but.png")));
    }//GEN-LAST:event_famousMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setState(Fammy.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new about().setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fammy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fammy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fammy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fammy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fammy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Site;
    private javax.swing.JButton famous;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel jmoviningbar;
    private javax.swing.JTextField view;
    // End of variables declaration//GEN-END:variables
}
